include:
  - sentinel-compose.yml

services:
  redis-master:
    image: redis:alpine
    container_name: redis-master
    command: redis-server --port 6379 --replica-announce-ip 127.0.0.1 --replica-announce-port 6379
    ports:
      - "6379:6379"
    networks:
      - redis-net

  redis-slave-1:
    image: redis:alpine
    container_name: redis-slave-1
    command: redis-server --port 6379 --replicaof redis-master 6379 --replica-announce-ip 127.0.0.1 --replica-announce-port 6380
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    networks:
      - redis-net

  redis-slave-2:
    image: redis:alpine
    container_name: redis-slave-2
    command: redis-server --port 6379 --replicaof redis-master 6379 --replica-announce-ip 127.0.0.1 --replica-announce-port 6381
    ports:
      - "6381:6379"
    depends_on:
      - redis-master
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
